name: digital_scale
description: Package to communicate with serial digital scale in flutter
homepage: https://github.com/sergiotucano/digital_scale
version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  roundabnt: ^0.0.3+1
  flutter_libserialport: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
